version: '2'

services:
  minio:
    image: minio/minio
    container_name: miniobkp
    ports:
      - 9000:9000
    env_file:
      - ./minio.env
    command: server /export
    volumes:
      - minio:/root/.minio/
      
  mc:
    image: minio/mc
    depends_on:
      - minio
    container_name: mcbkp
    env_file:
      - ./minio.env
    entrypoint: >
      /bin/sh -c "
      echo /usr/bin/mc config host a src https://play.minio.io:9000 $${PLAY_ACCESS_KEY} $${PLAY_SECRET_KEY};
      /usr/bin/mc config host a src https://play.minio.io:9000 $${PLAY_ACCESS_KEY} $${PLAY_SECRET_KEY};
      /usr/bin/mc config host a bkp http://localhost:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mirror -w src bkp;	
      mc policy public http://localhost:9000/pelanggaran
      "
volumes:
  minio:
